In [1]:
import numpy as np

In [3]:
# Create rank 1 array
x = np.array([1,2,3,4,5])

In [4]:
x[3] = 20

In [5]:
print(x)

[ 1  2  3 20  5]


In [7]:
# Create rank 2 array
X = np.arange(1,10).reshape(3,3)
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Delete value rank 1 array
x = np.array([1,2,3,4,5])
print(x)

# Deletes the indices in the array
x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [10]:
# Delete value in rank 2 array
Y = np.arange(1, 10).reshape(3,3)
print(Y)

W = np.delete(Y, 0, axis=0)
print("\n", W)

V = np.delete(Y, [0, 2], axis=1)
print("\n", V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [11]:
# Append values to rank 1 array
x = np.array([1,2,3,4,5])
print(x)

x = np.append(x, 6)
print(x)

x = np.append(x, [7,8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [16]:
# Append values to rank 2 array
Y = np.arange(1,10).reshape(3,3)
print(Y)

# Append Row
W = np.append(Y, [[10,11,12]], axis=0)
print(W)

# Append Column 
V = np.append(Y, [[10], [11], [12]], axis=1)
print(V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [17]:
# Insert list of elements in between indices in rank 1 array
x = np.array([1,2,5,6,7])
print(x)

x = np.insert(x, 2, [3, 4])
print(x)

[1 2 5 6 7]
[1 2 3 4 5 6 7]


In [24]:
# Insert list of elements in between indices in rank 2 array
Y = np.array([
    [1,2,3],
    [7,8,9]
])
print(Y)

# Insert Row
W = np.insert(Y, 1, [4,5,6], axis=0)
print(W)

# Insert Column
V = np.insert(Y, 1,5, axis=1)
print(V)

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 5 2 3]
 [7 5 8 9]]


In [25]:
# Stacking Arrays (Horizontally and Vertically)
# Using hstack, vstack
# They need to have the same number of rows or columns

x = np.arr([1,2])
Y = np.arr([
    [3,4],
    [5,6],
])
print(x)
print(Y)

# Stack vertically
a = np.vstack((x, Y))
print(a)


AttributeError: module 'numpy' has no attribute 'arr'