In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [5]:
print(x + y)
print(np.add(x, y))

print("- - - - - - - - - - - - - - ")

print(x - y)
print(np.subtract(x, y))

print("- - - - - - - - - - - - - - ")

print(x * y)
print(np.multiply(x, y))

print("- - - - - - - - - - - - - - ")

print(x / y)
print(np.divide(x, y))

[ 6  8 10 12]
[ 6  8 10 12]
- - - - - - - - - - - - - - 
[-4 -4 -4 -4]
[-4 -4 -4 -4]
- - - - - - - - - - - - - - 
[ 5 12 21 32]
[ 5 12 21 32]
- - - - - - - - - - - - - - 
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5,6,7, 8]).reshape(2,2)

print(X)
print("- - - - - - - - - - - - - - ")
print(Y)

[[1 2]
 [3 4]]
- - - - - - - - - - - - - - 
[[5 6]
 [7 8]]


In [9]:
print(X + Y)


print("- - - - - - - - - - - - - - ")
print(X - Y)


print("- - - - - - - - - - - - - - ")
print(X * Y)


print("- - - - - - - - - - - - - - ")
print(X / Y)


[[ 6  8]
 [10 12]]
- - - - - - - - - - - - - - 
[[-4 -4]
 [-4 -4]]
- - - - - - - - - - - - - - 
[[ 5 12]
 [21 32]]
- - - - - - - - - - - - - - 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [14]:
# Get sqrt and exponential of each element
print(x)

print("- - - - - - - - - - - - - - ")
print(np.sqrt(x))

print("- - - - - - - - - - - - - - ")
print(np.exp(x))

print("- - - - - - - - - - - - - - ")
print(np.power(x, 2))

[1 2 3 4]
- - - - - - - - - - - - - - 
[1.         1.41421356 1.73205081 2.        ]
- - - - - - - - - - - - - - 
[ 2.71828183  7.3890561  20.08553692 54.59815003]
- - - - - - - - - - - - - - 
[ 1  4  9 16]


In [16]:
# Statistical Methods
print(X)

print('average of all: ', X.mean())

print('average of columns:', X.mean(axis= 0))

print('average of rows:', X.mean(axis= 1))

[[1 2]
 [3 4]]
average of all:  2.5
average of columns: [2. 3.]
average of rows: [1.5 3.5]


In [17]:
print(X)

print('sum of all:', X.sum())

print('sum of columns:', X.sum(axis= 0))

print('sum of rows:', X.sum(axis= 1))

[[1 2]
 [3 4]]
sum of all:  10
sum of columns: [4 6]
sum of rows: [3 7]


In [20]:
# Standard Deviation
print("Standard Deviation:", X.std())
print("Median:", np.median(X))
print("Min:", X.min())
print("Max:", X.max())

Standard Deviation: 1.118033988749895
Median: 2.5
Min: 1
Max: 4


In [23]:
# Broadcasting
# Behind the scenes numpy is created a rank 2 array with the same
# shape in order to effieciently do arithmetic operations

print(X)
print("- - - - - - - - - - - - - - ")

print(X + 3)
print("- - - - - - - - - - - - - - ")

print(X - 3)
print("- - - - - - - - - - - - - - ")

print(X * 3)
print("- - - - - - - - - - - - - - ")

print(X / 3)

[[1 2]
 [3 4]]
- - - - - - - - - - - - - - 
[[4 5]
 [6 7]]
- - - - - - - - - - - - - - 
[[-2 -1]
 [ 0  1]]
- - - - - - - - - - - - - - 
[[ 3  6]
 [ 9 12]]
- - - - - - - - - - - - - - 
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [30]:
# Broadcasting pt.2
# Can be broadcasted if number if size of row = x

Y = np.arange(12).reshape(4,3)
x = np.arange(3)

print("Y:", Y)
print("x:", x)


print("- - - - - - - - - - - - - -\n")
print("Y + x:", Y + x)

Y: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
x: [0 1 2]
- - - - - - - - - - - - - - 
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [38]:
# Broadcasting pt.3 
# Can be broad casted if number of z.columns == Y.columns

Y = np.arange(12).reshape(4, 3)
z = np.arange(4).reshape(4, 1)

print("Y:", Y)
print("z:", z)
print("\n- - - - - - - - - - - - - -\n")
print("z + Y", z + Y)

Y: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
z: [[0]
 [1]
 [2]
 [3]]

- - - - - - - - - - - - - -

z + Y [[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
