In [1]:
import numpy as np

In [27]:
X = np.arange(25).reshape(5,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [8]:
print(X[X > 10])
print(X[X < 9])
print(X[(X > 3) & (X < 8)])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8]
[4 5 6 7]


In [14]:
# Assigning
X[(X >= 10) & (X < 15)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 -1]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
# Set operations
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [28]:
# Sorting
x = np.random.randint(1, 10, size=(10,))
print(x)

[3 3 9 8 2 5 5 8 9 3]


In [34]:
# np.sort() creates new copy, while x.sort() mutates the data
print(np.sort(x))
print(x)
print("- - - - - - - - -")
print(np.sort(np.unique(x)))
print("- - - - - - - - -")
x.sort()
print(x)

[2 3 3 3 5 5 8 8 9 9]
[2 3 3 3 5 5 8 8 9 9]
- - - - - - - - -
[2 3 5 8 9]
- - - - - - - - -
[2 3 3 3 5 5 8 8 9 9]


In [36]:
# Sorting rank 2 arrays
X = np.random.randint(1, 10, size=(5, 5))
print(X)
print("- - - - - - - - -")

# Sorting by column
print(np.sort(X, axis=0))
print("- - - - - - - - -")

# Sorty by row
print(np.sort(X, axis=1))


[[7 9 1 7 5]
 [8 5 2 2 7]
 [6 1 5 9 9]
 [3 7 5 6 9]
 [8 7 1 5 2]]
- - - - - - - - -
[[3 1 1 2 2]
 [6 5 1 5 5]
 [7 7 2 6 7]
 [8 7 5 7 9]
 [8 9 5 9 9]]
- - - - - - - - -
[[1 5 7 7 9]
 [2 2 5 7 8]
 [1 5 6 9 9]
 [3 5 6 7 9]
 [1 2 5 7 8]]
