In [1]:
import numpy as np

In [6]:
# Create rank 2 array
X = np.arange(1, 21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
print(X[1:4, 2:5])
print(X[1:, 2:])

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [18]:
print(X[:3, 2:])

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [19]:
print(X[:, 2])

[ 3  8 13 18]


In [20]:
print(X[:, 2:3])

[[ 3]
 [ 8]
 [13]
 [18]]


In [28]:
# Copying arrays
X = np.arange(0,20).reshape(4,5)

x = X[:3, 2:].copy()
# OR
x = np.copy(X[:3, 2:])

print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
# Selecting by indices
indices = np.array([1,3])
print(indices)

y = X[indices, :]
print(y)

z = X[:, indices]
print(z)

[1 3]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [29]:
# Extracting elements diagonally from numpy array
z = np.diag(X)
print(z)


[ 0  6 12 18]


In [30]:
# Move 1 more index
z = np.diag(X, k=1)
print(z)

[ 1  7 13 19]


In [31]:
# Extract unique elemeents in array
X = np.array([
    [1,2,3],
    [5,2,8],
    [1,2,3]
])

print(np.unique(X))

[1 2 3 5 8]
